/usr/lib64/qt5/qml/Qt/labs/sharedimage
/usr/lib64/qt4/imports/Qt/labs/shaders
/usr/lib64/libreoffice/share
/usr/lib64/libreoffice/program/shell
/usr/lib/rpm/platform/sh3-linux
/usr/lib/rpm/platform/sh4a-linux
/usr/lib/rpm/platform/sh4-linux
/usr/lib/rpm/platform/sh-linux
/usr/local/share
/usr/share
/usr/share/nvim/runtime/pack/dist/opt/shellmenu
/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/share
/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/shebang-command
/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sha
/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/shebang-regex
/usr/share/locale/shs
/usr/share/locale/shn
/usr/share/doc/sheepdog
/usr/share/doc/shared-mime-info
/usr/share/doc/shadow-utils
/usr/share/gnome/shutdown
/usr/share/vim/vim82/pack/dist/opt/shellmenu
/usr/share/X11/xkb/symbols/sharp_vndr
/usr/share/code/resources/app/extensions/shellscript
/usr/share/code/resources/app/extensions/shaderlab
/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess
/usr/share/licenses/shared-mime-info
/usr/share/licenses/shadow-utils
/usr/src/kernels/5.13.14-100.fc33.x86_64/sound/sh
/usr/src/kernels/5.13.14-100.fc33.x86_64/sound/soc/sh
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh/kernel/cpu/sh4a
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh/kernel/cpu/sh2
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh/kernel/cpu/sh3
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh/kernel/cpu/sh4
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh/kernel/cpu/shmobile
/usr/src/kernels/5.13.14-100.fc33.x86_64/arch/sh/kernel/cpu/sh2a
/usr/src/kernels/5.13.14-100.fc33.x86_64/drivers/sh
/usr/src/kernels/5.13.14-100.fc33.x86_64/drivers/dma/sh
/usr/src/kernels/5.13.14-100.fc33.x86_64/drivers/gpu/drm/shmobile
/usr/src/kernels/5.13.14-100.fc33.x86_64/tools/perf/arch/sh
/var/lib/selinux/targeted/active/modules/100/shorewall
/var/lib/sheepdog
/var/lib/gdm/.local/share
/sys/kernel/slab/shared_policy_node
/sys/kernel/slab/shmem_inode_cache
/sys/bus/pci/drivers/shpchp
/sys/module/shpchp
/root/.local/share
/root/.local/share/nvim/shada
/run/systemd/shutdown
/dev/shm
